<?php
/**
 * Mega-menu panel styling.
 *
 * Attaches assets/styles/ollie-mega-menu.css to `ollie/mega-menu`, so the panel
 * styles load only on pages where a mega menu renders.
 *
 * ## Why this needs a module at all
 *
 * `enqueue_custom_block_styles()` in functions.php auto-enqueues by filename
 * convention — `core-button.css` attaches to `core/button` — and deliberately
 * globs `core-*.css` only. `ollie/mega-menu` is not a core block, so it has no
 * place in that scan; a non-core block's stylesheet is registered by its own
 * module here, which is the arrangement functions.php documents.
 *
 * ## Why this belongs in the theme
 *
 * inc/README.md admits "styling and presentation glue for third-party plugin
 * markup that a theme.json or styles/** partial genuinely cannot reach", and
 * that is exactly what this is: the panel's container markup is generated by
 * Ollie Menu Designer's own render.php, so no block-style variation can carry
 * these rules.
 *
 * It is also *only* styling. The same README bans "sticky-header, mobile-menu
 * and banner behaviour" from this directory, and none of that is here — this
 * module registers one stylesheet and nothing else. The mega menu's behaviour is
 * the plugin's (Interactivity API), the menu content is `wp_navigation` content
 * resolved by SD Enhancements, and the sticky header is a handful of CSS rules
 * in assets/styles/core-group.css with no JavaScript at all.
 *
 * @package sd-theme-2026
 */

namespace SdTheme2026;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Register the mega-menu panel stylesheet against the block that renders it.
 *
 * `wp_enqueue_block_style()` is lazy: the stylesheet is printed only when the
 * block appears on the page, and inlined when it is small enough. Passing `path`
 * is what enables that inlining, so it is set alongside `src`.
 */
function enqueue_mega_menu_style() {
	$relative = 'assets/styles/ollie-mega-menu.css';

	wp_enqueue_block_style(
		'ollie/mega-menu',
		array(
			'handle' => 'sd-theme-2026-block-ollie-mega-menu',
			'src'    => get_theme_file_uri( $relative ),
			'path'   => get_theme_file_path( $relative ),
			'ver'    => asset_version( $relative ),
		)
	);
}
add_action( 'init', __NAMESPACE__ . '\\enqueue_mega_menu_style' );
